[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

#自己维护
ruleset=🚀 节点选择,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/Oneself.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/Oneself-Direct.list
ruleset=💬 Ai,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/AI.list
ruleset=🇯🇵 日本自动(x1),https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/Japan.list

;游戏下载
ruleset=🎮 游戏下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🎮 游戏下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/GameDownload/GameDownload.list

;设置规则标志位
ruleset=🔌 国外DNS,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/ForeignDNS.list
#ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
#ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=💿 国外网盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=💿 国外网盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PikPak/PikPak.list
ruleset=💿 国外网盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Docker/Docker.list
ruleset=💿 国外网盘,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/NatDisk.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
#OpenAi
ruleset=💬 Ai,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
#Gemini
ruleset=💬 Ai,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Gemini.list
#第三方AI配置
ruleset=💬 Ai,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
#ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/Magic-riding/ACL4SSR/refs/heads/make/Oneself-Game.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
#ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list
ruleset=📹 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=📟 Twitch,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Twitch/Twitch.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bahamut/Bahamut.list
#ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list
ruleset=🖥️ GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
#Reddit节点
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Reddit/Reddit.list
#docker节点
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Docker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择(只有1倍率)`[]🚀 手动切换`[]🔮 负载均衡(自动选择)`🎮 游戏加速`[]🇭🇰 香港故转`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾故转`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城故转`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本故转`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国故转`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国故转`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🚀 手动切换`select`^(?!(.*?(重置|刷新))).*$
custom_proxy_group=♻️ 自动选择(只有1倍率)`url-test`^(?!(.*?(重置|刷新))|.*(?:[1-9]\d*0[xX]|[2-9][xX]|[xX][2-9])).*$`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🔮 负载均衡(自动选择)`load-balance`^(?!(.*?(重置|刷新))).*$`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=📲 电报消息`select`下载节点(x1)`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🖥️ GitHub`select`下载节点(x1)`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=💬 Ai`select`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
#custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇺🇲 美国自动(x1)`[]🇭🇰 香港自动(x1)`[]🇨🇳 台湾自动(x1)`[]🇸🇬 狮城自动(x1)`[]🇯🇵 日本自动(x1)`[]🇰🇷 韩国自动(x1)`[]DIRECT
custom_proxy_group=📹 TikTok`select`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]DIRECT
custom_proxy_group=📟 Twitch`select`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点
custom_proxy_group=🔌 国外DNS`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=💿 国外网盘`select`下载节点(x1)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🎮 游戏下载`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🎮 游戏加速`select`[]DIRECT`(游戏)
#custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择(只有1倍率)`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择(只有1倍率)
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]♻️ 自动选择(只有1倍率)`[]🇭🇰 香港自动(x1)`[]🇭🇰 香港节点`[]🇨🇳 台湾自动(x1)`[]🇨🇳 台湾节点`[]🇸🇬 狮城自动(x1)`[]🇸🇬 狮城节点`[]🇯🇵 日本自动(x1)`[]🇯🇵 日本节点`[]🇰🇷 韩国自动(x1)`[]🇰🇷 韩国节点`[]🇺🇲 美国自动(x1)`[]🇺🇲 美国节点
custom_proxy_group=🇭🇰 香港自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(香港|港|HK|hk|Hong\sKong|HongKong|hongkong)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇭🇰 香港节点`select`(香港|港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=🇭🇰 香港故转`fallback`[]🇭🇰 香港节点`[]🇭🇰 香港自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇯🇵 日本自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=🇯🇵 日本故转`fallback`[]🇯🇵 日本节点`[]🇯🇵 日本自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇺🇲 美国自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(美国|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,3000,3
custom_proxy_group=🇺🇲 美国节点`select`(美国|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇺🇲 美国故转`fallback`[]🇺🇲 美国节点`[]🇺🇲 美国自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇨🇳 台湾自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(台湾|台|新北|彰化|TW|Taiwan)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇨🇳 台湾节点`select`(台湾|台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇨🇳 台湾故转`fallback`[]🇨🇳 台湾节点`[]🇨🇳 台湾自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇸🇬 狮城自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(新加坡|坡|狮城|SG|Singapore)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇸🇬 狮城故转`fallback`[]🇸🇬 狮城节点`[]🇸🇬 狮城自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇰🇷 韩国自动(x1)`url-test`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(韩国|KR|Korea|KOR|首尔|韩|韓)(?!.*\b\d+[xX])`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇰🇷 韩国节点`select`(韩国KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=🇰🇷 韩国故转`fallback`[]🇰🇷 韩国节点`[]🇰🇷 韩国自动(x1)`http://www.apple.com/library/test/success.html`300,1000,3
custom_proxy_group=🇭🇰 香港DNS(x1)`select`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b).*?(香港|港|HK|hk|Hong\sKong|HongKong|hongkong)(?!.*\b\d+[xX])
custom_proxy_group=🇭🇰 下载节点(x1)`select`^(?!.*\b(?:[2-9]|[1-9]\d+)[xX]\b)(?:Mitce.*|.*美国-下载-realty.*)(?!.*\b\d+[xX])
;设置分组标志位

; useless?
enable_rule_generator=true
overwrite_original_rules=true

; [common]
append_proxy_type=false
; proxy_subscription=SYSTEM
; proxy_ruleset=SYSTEM
proxy_config=SYSTEM
; get out of here (!
; clash_rule_base=https://raw.githubusercontent.com/DoingDog/clashconf/main/base.yaml
exclude_remarks=(到期|剩余流量|时间|官网|产品|平台|更新订阅|客服)
; do you play games?
; exclude_remarks=(G-|游戏)

; [node_pref]
; love tls1.3
tls13_flag=true
; no you don't play games
udp_flag=true
; though useless
tcp_fast_open_flag=true
append_sub_userinfo=true
; no
;filter_deprecated_nodes=true
; looks better
clash_proxies_style=block
clash_use_new_field_name=true

; [userinfo]
; useless?
; stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
; time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6

; [managed_config]
config_update_interval = 86400

; [emojis]
; for you
add_emoji=true
remove_old_emoji=true
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(巴基斯坦|Pakistan|PAKISTAN),🇵🇰
emoji=(巴林|Bahrain),🇧🇭
emoji=(柬埔寨|Cambodia),🇰🇭
emoji=(奥地利|奧地利|Austria|维也纳),🇦🇹
emoji=(沙特|利雅得|Saudi Arabia|Saudi),🇸🇦
emoji=(智利|Chile|CHILE),🇨🇱
emoji=(新西蘭|新西兰|New Zealand),🇳🇿
emoji=(埃及|Egypt),🇪🇬
emoji=(马恩岛|馬恩島|Isle of Man|Mannin),🇮🇲
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(蒙古|Mongolia),🇲🇳
emoji=(秘鲁|祕魯|Peru),🇵🇪
emoji=(哥伦比亚|Colombia),🇨🇴
emoji=(爱沙尼亚|Estonia),🇪🇪
emoji=(马其顿|馬其頓|Macedonia),🇲🇰
emoji=(马耳他|Malta),🇲🇹
emoji=(委内瑞拉|Venezuela),🇻🇪
emoji=(波黑共和国|波黑|Bosnia and Herzegovina),🇧🇦
emoji=(格魯吉亞|格鲁吉亚|Georgia),🇬🇪
emoji=(阿爾巴尼亞|阿尔巴尼亚|Albania),🇦🇱
emoji=(哥斯达黎加|Costa Rica),🇨🇷
emoji=(突尼斯|Tunisia),🇹🇳
emoji=(巴拿马|巴拿馬|Panama),🇵🇦
emoji=(伊朗|Iran),🇮🇷
emoji=(约旦|約旦|Jordan),🇯🇴
emoji=(乌拉圭|烏拉圭|Uruguay),🇺🇾
emoji=(肯尼亚|肯尼亞|Kenya),🇰🇪
emoji=(吉尔吉斯坦|吉尔吉斯斯坦|Kyrghyzstan),🇰🇬
emoji=(尼泊尔|Nepal),🇳🇵
emoji=(科索沃|Kosovo),🇽🇰
emoji=(摩洛哥|Morocco),🇲🇦
emoji=(安道尔|Andorra),🇦🇩
emoji=(巴拉圭|Paraguay),🇵🇾
emoji=(亚美尼亚|亞美尼亞|Armenia),🇦🇲
emoji=(留尼汪|留尼旺|Réunion|Reunion),🇷🇪
emoji=(库拉索|庫拉索|Curaçao),🇨🇼
emoji=(Israel|以色列),🇮🇱
emoji=(Latvia|Latvija|拉脱维亚),🇱🇻
emoji=(孟加拉|Bengal),🇧🇩
emoji=(Finland|芬兰|芬蘭|赫尔辛基),🇫🇮
emoji=(哈萨克斯坦|哈薩克斯坦|Kazakhstan),🇰🇿
emoji=(斯洛文尼亚|斯洛文尼亞|Slovenia),🇸🇮
emoji=(立陶宛|Lithuania),🇱🇹
emoji=(斯里兰卡|斯里蘭卡|Sri Lanka),🇱🇰
emoji=(乌兹别克斯坦|烏茲別克斯坦|Uzbekistan),🇺🇿
emoji=(老挝|老挝|Laos),🇱🇦
emoji=(Ireland|IRELAND|爱尔兰|愛爾蘭|都柏林),🇮🇪
emoji=(文莱|BRN |Negara Brunei Darussalam),🇧🇳
emoji=(BE |BE-|BE_|BE0|BE1|BE2|比利時|比利时),🇧🇪
emoji=(UA |UA-|UA_|UA0|UA1|UA2|烏克蘭|乌克兰|基辅|Ukraine),🇺🇦
emoji=(克罗地亚|HR |HR-|HR_|HR0|HR1|HR2|克羅地亞|Croatia),🇭🇷
emoji=(尼日利亚|NG |NG-|NG_|NG0|NG1|NG2|尼日利亞|拉各斯|Nigeria),🇳🇬
emoji=(斯洛伐克|SK |SK-|SK_|SK0|SK1|Slovakia),🇸🇰
emoji=(馬提尼克|马提尼克|MQ |MQ-|MQ_|MQ0|MQ1|Martinique),🇲🇶
emoji=(ZA |ZA-|ZA_|ZA0|South Africa|南非|Johannesburg),🇿🇦
emoji=(RW |RW-|RW_|RW0|Rwanda|卢旺达),🇷🇼
emoji=(CZ |CZ-|CZ_|CZ0|Czechia|捷克),🇨🇿
emoji=(BG |BG-|BG_|BG0|保加利亚|保加利亞|Bulgaria),🇧🇬
emoji=(RS |RS-|RS_|RS0|RS1|RS2|塞尔维亚|塞爾維亞|Seville|Sevilla),🇷🇸
emoji=(摩爾多瓦|MD |MD-|MD_|MD0|MD1|MD2|摩尔多瓦|Moldova),🇲🇩
emoji=(DK |DK-|DK_|DK0|DK1|DK2|DNK|丹麦|丹麥|Denmark),🇩🇰
emoji=(ES |ES-|ES_|ES0|ES1|ES2|西班牙|Spain),🇪🇸
emoji=(FR |FR-|FR_|FR0|FR1|FR2|France|法国|法國|巴黎),🇫🇷
emoji=(UK |GB |UK-|UK_|GB-|UK0|GB0|UK1|GB1|England|United Kingdom|英国|伦敦),🇬🇧
emoji=(MO |MO-|MO_|MO0|MO1|MO2|Macao|Macau|MAC|澳门|澳門|CTM),🇲🇴
emoji=(ID |IDN |ID-|ID_|ID0|ID1|ID2|Indonesia|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(India|IND|INDIA|印度|孟买|Mumbai|IN |IN-|IN_|IN0),🇮🇳
emoji=(IS |IS-|IS_|IS0|IS1|IS2|ISL|冰岛|冰島|Iceland),🇮🇸
emoji=(MEX|MX |MX-|MX_|MX0|MX1|MX2|墨西哥|Mexico|MEXICO),🇲🇽️
emoji=(MY |MY-|MY_|MY0|MY1|MY2|Malaysia|MALAYSIA|大馬|大马|馬來西亞|吉隆坡|馬來|马来),🇲🇾
emoji=(NL |NL-|NL_|NL0|NL1|NL2|Netherlands|荷兰|荷蘭|尼德蘭|阿姆斯特丹),🇳🇱
emoji=(PH |PH-|PH_|PH0|PH1|PH2|Philippines|菲律宾|菲律賓),🇵🇭
emoji=(RO |RO-|RO_|RO0|RO1|RO2|罗马尼亚|Romania|Rumania),🇷🇴
emoji=(BY |BY-|BY_|BY0|BY1|BY2|白俄罗斯|白俄羅斯|White Russia|Republic of Belarus|Belarus),🇧🇾
emoji=(KP |KP-|KP_|朝鲜|North Korea),🇰🇵
emoji=(SE |SE-|SE_|SE0|SE1|SE2|Sweden|瑞典),🇸🇪
emoji=(TH |TH-|TH_|TH0|TH1|TH2|Thailand|泰国|泰國|曼谷),🇹🇭
emoji=(TR |TR-|TR_|TR0|TR1|TR2|TUR|Turkey|土耳其|伊斯坦布尔),🇹🇷
emoji=(VN |VN-|VN_|VN0|VN1|VN2|越南|胡志明市|Vietnam),🇻🇳
emoji=(Italy|IT |IT-|IT_|IT0|IT1|IT2|Nachash|意大利|米兰|義大利),🇮🇹
emoji=(United Arab Emirates|阿联酋|AE |AE-|AE_|AE0|AE1|AE2|迪拜|Dubai),🇦🇪
emoji=(BR |BR-|BR_|BR0|BR1|BR2|Brazil|巴西|圣保罗),🇧🇷
emoji=(AR |AR-|AR_|AR0|AR1|AR2|Argentina|阿根廷),🇦🇷
emoji=(Norway|挪威|NO |NO-|NO_|NO0|NO1|NO2),🇳🇴
emoji=(PL |PL-|PL_|PL0|PL1|PL2|POL|波兰|波蘭|Porland),🇵🇱
emoji=(CY |CY-|CY_|CY0|CY1|CY2|塞浦路斯),🇨🇾
emoji=(厄瓜多尔|EC |EC-|EC_|EC0|EC1|EC2|Ecuador),🇪🇨
emoji=(波多黎各|PR |PR-|PR_|PR0|PR1|PR2),🇵🇷
emoji=(黎巴嫩|LB |LB-|LB_|LB0|LB1|LB2|Lebanon),🇱🇧
emoji=(LU |LU-|LU_|LU0|LU1|LU2|卢森堡),🇱🇺
emoji=(HU |HU-|HU_|HU0|HU1|HU2|匈牙利|Hungary),🇭🇺
emoji=(CH |CH-|CH_|CH0|CH1|CH2|瑞士|苏黎世|Switzerland),🇨🇭
emoji=(DE |DE-|DE_|DE0|DE1|DE2|German|GERMAN|德国|德國|法兰克福|京德|滬德|廣德|沪德|广德),🇩🇪
emoji=(希腊|希臘|Greece|GR |GR-|GR_|GR0|GR1|GR2),🇬🇷
emoji=(KR |KR-|KR_|KR0|KR1|KR2|Korea|KOR|韩国|首尔|韓|春川),🇰🇷
emoji=(RU |RU-|RU_|RU0|RU1|RU2|RUS|Russia|俄罗斯|毛子|俄国|俄羅斯|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|京俄|杭俄|廣俄|滬俄|广俄|沪俄),🇷🇺
emoji=(AU |AU-|AU_|AU0|AU1|AU2|Australia|Sydney|澳大利亚|澳洲|墨尔本|悉尼|土澳|京澳|廣澳|滬澳|沪澳|广澳),🇦🇺
emoji=(CA |CA-|CA_|CA0|CA1|CA2|Canada|CANADA|CAN|Waterloo|加拿大|蒙特利尔|温哥华|楓葉|枫叶|滑铁卢|多伦多),🇨🇦
emoji=(US|USA|America|United States|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|矽谷|拉斯维加斯|洛杉矶|圣何塞|圣荷西|圣克拉拉|西雅图|芝加哥|沪美|哥伦布|纽约),🇺🇸
emoji=(TW|Taiwan|TAIWAN|台湾|台北|台中|新北|彰化|CHT|台|HINET),🇹🇼
emoji=(SG|SG-|SG_|Singapore|SINGAPORE|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新|广新|廣新|滬新),🇸🇬
emoji=(JP|JP-|JP_|Japan|JAPAN|日本|东京|大阪|埼玉|穗日|川日|中日|泉日|杭日|深日|辽日|广日|Tokyo),🇯🇵
emoji=(HK|Hongkong|Hong Kong|HongKong|HONG KONG|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港),🇭🇰
emoji=(CN|CN-|CN_|China|回国|中国|中國|江苏|北京|上海|广州|深圳|杭州|徐州|青岛|宁波|镇江|back),🇨🇳
emoji=(EU|EU-|EU_|欧盟|欧罗巴|欧洲|European),🇪🇺
emoji=(亚洲|Asia),🌏
emoji=(流媒体|Netflix|NETFLIX|NF|视频|解锁),📺
emoji=(DL|下载|大流量|大数据),⚡️
emoji=(GA|游戏),🎮

; [advanced]
; better than fail
skip_failed_links=true

; modify as you like
; luck

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

